// @/workers/GettingRandomGreeting.js
self.onmessage = function() {

  const greetings = [
    "Hello!",
    "Hi there!",
    "Greetings!",
    "Hey!",
    "Howdy!",
    "Welcome!",
    "Good day!",
    "Hello there!",
    "Hi!",
    "What's up!",
    "Bonjour!",
    "Hola!",
    "Ciao!",
    "Hallo!",
    "Olá!",
    "Namaste!",
    "Konnichiwa!",
    "Salam!",
    "Shalom!",
    "Hej!",
    "Sawubona!",
    "Zdravstvuyte!",
    "Merhaba!",
    "Szia!",
    "Yasou!",
    "Salut!",
    "Hei!",
    "Sawasdee!",
    "Dzień dobry!",
    "Kalimera!",
    "Ahoj!",
    "Helo!",
    "Tere!",
    "Kamusta!",
    "Kia ora!",
    "Jambo!",
    "Marhaba!",
    "Hujambo!",
    "Cześć!",
    "Helo!",
    "Zdravo!",
    "Salut!",
    "Zdravo!",
    "Selam!",
    "Aloha!",
    "Ahoy!",
    "G'day!",
    "Howdy!",
    "Witaj!",
    "Bună!",
    "Hei!",
    "Hallo!",
    "Hí!",
    "Laba diena!",
    "Goeie dag!",
    "Vitajte!",
    "Xin chào!",
    "Bonjour tout le monde!",
    "Hola a todos!",
    "Konnichiwa sekai!",
    "Guten Tag!",
    "Ola Mundo!",
    "Helo Byd!",
    "Bonjour le monde!",
    "Hola Mundo!",
    "Hallo Wereld!",
    "Ciao Mondo!",
    "Olá Mundo!",
    "Hej Verden!",
    "Kumusta Mundo!",
    "Lugna Mundo!",
    "Szia Világ!",
    "Merhaba Dünya!",
    "Hola Mundo!",
    "Bonjour le monde!",
    "Hello World!",
    "Hey World!",
    "Hi World!",
    "Greetings World!",
    "Howdy World!",
    "Welcome World!",
    "Good Day World!",
    "Hello Everyone!",
    "Hi Everyone!",
    "Greetings Everyone!",
    "Hey Everyone!",
    "Welcome Everyone!",
    "Good Day Everyone!"
];

  // Pick a random greeting
  const randomGreeting = greetings[Math.floor(Math.random() * greetings.length)];
  // Send the greeting back to the main thread
  self.postMessage(randomGreeting);
};
